---
- name: Configure network adapter
  hosts: all
  gather_facts: no

  vars:
    network:
      ip: 192.168.1.160
      subnet: 255.255.255.0
      gateway: 192.168.1.1
      dns: ["192.168.1.1", "1.1.1.1"]
      
    network_switch: 'SW-1G'

    vms:
      - name: test-{{ env }}

  tasks:
    - name: Configure network
      win_shell: |
        Get-VMNetworkAdapter -VMName {{ vms[0].name }} | Set-VMNetworkConfiguration -IPAddress {{ network.ip }} -Subnet {{ network.subnet }} -DNSServer {{ network.dns|join(",") }} -DefaultGateway {{ network.gateway }}
