---
- hosts: all
  become: true
  gather_facts: False
  vars:
    users:
      - name: a-ytissot
        ssh_key: /SSH_Keys/Yann.pub
      - name: a-nkirchhofer
        ssh_key: /SSH_Keys/Nicolas.pub
  tasks:
    - name: Create users and add ssh keys
      loop: "{{ users }}"
      user:
        name: "{{ item.name }}"
        shell: /bin/bash
        create_home: yes
        groups: sudo
      register: user_result

    - name: Read local ssh key
      set_fact:
        local_ssh_key: "{{ lookup('file', item.ssh_key) }}"
      loop: "{{ users }}"
      when: user_result.changed

    - name: Set authorized key taken from file
      authorized_key:
        user: "{{ item.name }}"
        state: present
        key: "{{ local_ssh_key }}"
      loop: "{{ users }}"
      when: user_result.changed

    - name: Disable password authentication
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication'
        line: 'PasswordAuthentication no'
        state: present
      notify: Restart ssh

  handlers:
    - name: Restart ssh
      service:
        name: ssh
        state: restarted
