- name: Configure DHIS VM
  hosts: "GCH001VDHIS001Y"
  become: true
  gather_facts: true
  vars:
    public_keys_file: /SSH_Keys/ssh_dhis    
    
  tasks:
    - name: Set root authorized_keys
      authorized_key:
        user: "root"
        key: "{{ lookup('file', public_keys_file) }}"
        state: present