- hosts: localhost

  vars:
    ansible_user: "{{ lookup('env', 'ANSIBLE_USER') }}"
    ansible_password: "{{ lookup('env', 'ANSIBLE_PASSWORD') }}"

  tasks:
    - name: 2
      debug: 
        msg: "{{ ansible_user }}"