- hosts: localhost
  tasks:
    - name: 2
      debug: 
        msg: "Avant d'appeler un autre playbook"

- hosts: localhost
  tasks:
    - name: 2
      debug:
        msg: "Après avoir appelé un autre playbook"