- name: Deploy VM on Hyper-V
  hosts: "{{ lookup('env', 'code_projet') }}PHYP001P"
  gather_facts: no

  vars:
    #VM definition
    default_generation: 2
    cpu: 4
    memory: 4096MB

    #Switch definition
    network_switch: 'SW-1G'
    
    #ISO definition
    src_iso: 'C:\Fiwi_IT_TEST\Iso\FINAL.iso'
    
    #VHDX naming and sizing
    vhdx_suffixes:
      #/var
      - name: 'VAR'
        size: '20GB'
      #/var/log
      - name: 'VARLOG'
        size: '10GB'
      #/home    
      - name: 'HOME'
        size: '10GB'
      #/home/dhis2
      - name: 'DHIS2'
        size: '10GB'
      #home/bckp
      - name: 'BCKP'
        size: '10GB'
        
    #VHDX location
    vhdx_location:
      - 'C:\ClusterStorage\Volume1\Hyper-V\DHIS'
      
    #Network parameters
    network:
      ip_start: 150
      ip_end: 159
      subnet_mask: '255.255.255.0'
      gateway: "{{ subnet }}.1"
      dns:
        - "{{ subnet }}.1"
        - '8.8.8.8'
        
    #Hyper-V
    hyperv_suffix: "PHYP001P"
    dhcp_suffix: "VDCRO001P"
    
    #VM Type
    vm_type: "DHIS"
    
    #...
    username: a-ydumas
    password: Vg43bX87?uiCK1IhUL!
    
       
  #Let's goooooooo
  tasks:
    #First we check the IP range
    - name: Check IP range of the host
      set_fact:
        subnet: "{{ lookup('dig', inventory_hostname).split('.')[0] + '.' + lookup('dig', inventory_hostname).split('.')[1] + '.' + lookup('dig', inventory_hostname).split('.')[2] }}"

    - name: INFO (IP range)
      debug:
        msg: "It's {{ subnet }}" 
  
    #We look at existings VMs regarding our environment variables by checking the host
    #We register our future VM's name as a variable "next_vm_number" for the current playbook
    - name: Determine next available VM name (based on env)
      win_shell: |
        $code_projet = "{{ lookup('env', 'code_projet') }}"
        $type_machine = "{{ vm_type }}"
        $environnement = "{{ lookup('env', 'environment') }}"

        $regex = "^${code_projet}V${type_machine}(\d+)$environnement$"
        $vm_names = Get-VM | Select-Object -ExpandProperty Name
        $vm_numbers = $vm_names | ForEach-Object { if ($_ -match $regex) { [int]$matches[1] } } | Sort-Object
        $next_vm_number = 1
        foreach ($number in $vm_numbers) {
          if ($number -gt $next_vm_number) { break }
          $next_vm_number += 1
        }
        $next_vm_number.ToString("D3")
      register: next_vm_number
      
    - name: INFO (VM Name)
      debug:
        msg: "Next VM name will be {{ lookup('env', 'code_projet') }}V{{ vm_type }}{{ next_vm_number.stdout | trim }}{{ lookup('env', 'environment') }}" 
    
    #We create the VM and power it for 10 seconds so the vnet card gets initialized and obtains a MAC address from host. We save the MAC address.
    - name: VM Creation ({{ lookup('env', 'code_projet') }}V{{ vm_type }}{{ next_vm_number.stdout | trim }}{{ lookup('env', 'environment') }})
      win_shell: |
        $vm_name = '{{ lookup('env', 'code_projet') }}V{{ vm_type }}{{ next_vm_number.stdout | trim }}{{ lookup('env', 'environment') }}'
        $vm = Get-VM -Name $vm_name
        if ($null -eq $vm) {
          $vm = New-VM -Name $vm_name -Generation {{ default_generation }} -MemoryStartupBytes {{ memory }} -SwitchName {{ network_switch }}
          Set-VMProcessor -VM $vm -Count {{ cpu }}
          Start-VM -Name $vm_name # Start the VM
          # Start VM so network card gets a MAC address ----------------------- ANSIBLE COMMENT
          Start-Sleep -Seconds 1
          Stop-VM -TurnOff -Name $vm_name
          # --- and turn off after 1 seconds --------------------------------- ANSIBLE COMMENT
        }                
        $vm.NetworkAdapters[0].MacAddress
      register: mac_address

############################DOUBLE QUOTES OBLIGATOIRES ?######################
######Sinon {{ vhdx_location }} =       - 'C:\ClusterStorage\Volume1\Hyper-V\DHIS'#######
    - name: Create and attach OS VHDX
      win_shell: |
        $vm_name = '{{ lookup('env', 'code_projet') }}V{{ vm_type }}{{ next_vm_number.stdout | trim }}{{ lookup('env', 'environment') }}'
        $path = "C:\\ClusterStorage\\Volume1\\Hyper-V\\DHIS\\${vm_name}-OS.vhdx"
        if (-not (Test-Path $path)) {
          New-VHD -Path $path -Dynamic -SizeBytes 15GB
        }
        $vm = Get-VM -Name $vm_name
        if ($null -ne $vm) {
          $existingVhd = Get-VMHardDiskDrive -VMName $vm.Name | Where-Object { $_.Path -eq $path }
          if ($existingVhd -eq $null) {
            Add-VMHardDiskDrive -VM $vm -Path $path
          }
        }          
      register: vhdx_exists 

    # We check for the next available IP based on playbook defined range ()
    - name: Determine first available IP (based on host)
      win_shell: |
        $ipStart = {{ network.ip_start }}
        $ipEnd = {{ network.ip_end }}
        $subnet = "{{ subnet }}" # Using the previously set subnet variable
        for ($i=$ipStart; $i -le $ipEnd; $i++) {
            $ip = $subnet + "." + $i
            if (!(Test-Connection -ComputerName $ip -Count 1 -Quiet)) {
                return $ip
            }
        }
        throw "No free IP address found in the specified range."
      register: free_ip
      
    - name: INFO (Free IP)
      debug:
        msg: "IP will be {{ free_ip.stdout | trim }}" 

    # We pre-register amongst the local RODC especially for DNS
    - name: Local RODC DHCP+DNS pre-registration
      win_shell: |
        $password = "{{ lookup('env', 'p') }}" | ConvertTo-SecureString -AsPlainText -Force
        $credential = New-Object System.Management.Automation.PSCredential ('{{ lookup('env', 'u') }}', $password)
        $subnet = "{{ subnet }}.0" # Removed quotes around 'subnet'
        $name = "{{ lookup('env', 'code_projet') }}V{{ vm_type }}{{ next_vm_number.stdout | trim }}{{ lookup('env', 'environment') }}.ocg.msf.org"
        $ipaddress = "{{ free_ip.stdout | trim }}"
        $clientid = "{{ mac_address.stdout | trim }}" # Changed variable name

        $scriptBlock = {
          param($subnet, $name, $ipaddress, $clientid) # Changed parameter name
          Add-DhcpServerv4Reservation -ScopeID $subnet -Name $name -IPAddress $ipaddress -ClientId $clientid
        }

        Invoke-Command -ComputerName {{ lookup('env', 'code_projet') }}VRODC001P -Credential $credential -ScriptBlock $scriptBlock -ArgumentList $subnet, $name, $ipaddress, $clientid
        
    #Disabling secure boot before custom ISO install
    - name: Disable secure boot
      win_shell: |
        $vm_name = "{{ lookup('env', 'code_projet') }}V{{ vm_type }}{{ next_vm_number.stdout | trim }}{{ lookup('env', 'environment') }}"
        Set-VMFirmware -EnableSecureBoot Off -VMName $vm_name

    #Attach ISO to DVD
    - name: Attach ISO to VM
      win_shell: |
        $vm_name = "{{ lookup('env', 'code_projet') }}V{{ vm_type }}{{ next_vm_number.stdout | trim }}{{ lookup('env', 'environment') }}"
        $vm = Get-VM -Name $vm_name
        $dvdDrive = Get-VMDvdDrive -VM $vm | Where-Object { $_.ControllerLocation -eq "0" }
        if ($dvdDrive -ne $null)
        {
            Set-VMDvdDrive -VM $vm -ControllerNumber $dvdDrive.ControllerNumber -ControllerLocation $dvdDrive.ControllerLocation -Path "{{ src_iso }}"
        }
        else
        {
            try {
                Add-VMDvdDrive -VM $vm -ControllerNumber 0 -ControllerLocation 1 -Path "{{ src_iso }}"
            } catch {
                Write-Error "Failed to add DVD Drive: $_"
            }
        }                

    #Booting on defined ISO
    - name: Set VM to boot from DVD Drive
      win_shell: |
        $vm_name = '{{ lookup('env', 'code_projet') }}V{{ vm_type }}{{ next_vm_number.stdout | trim }}{{ lookup('env', 'environment') }}'
        $vm = Get-VM -Name {{ lookup('env', 'code_projet') }}V{{ vm_type }}{{ next_vm_number.stdout | trim }}{{ lookup('env', 'environment') }}
        $dvdDrive = Get-VMDvdDrive -VM $vm
        Set-VMFirmware -VM $vm -FirstBootDevice $dvdDrive                

    #Enable LIS... Why do I even comment
    - name: Enable Linux Integration Services
      win_shell: |
        $vm_name = '{{ lookup('env', 'code_projet') }}V{{ vm_type }}{{ next_vm_number.stdout | trim }}{{ lookup('env', 'environment') }}'
        Enable-VMIntegrationService -VMName $vm_name -Name 'Guest Service Interface'       

    #We power on the VM and wait for it to get an IP at the end of the autoinstall
    - name: ~30min | Power on and wait OS autoinstall... (-> ip in Hyper-V)
      win_shell: |
        $vm_name = '{{ lookup('env', 'code_projet') }}V{{ vm_type }}{{ next_vm_number.stdout | trim }}{{ lookup('env', 'environment') }}'
        $vm = Get-VM -Name $vm_name
         if ($vm.State -eq 'Off') {
           Start-VM -VM $vm
         }                
        $vm = Get-VM -Name $vm_name
        do {
          Start-Sleep -Seconds 10
          $vm = Get-VM -Name $vm_name
          $ip = ($vm.NetworkAdapters.IPAddresses | Where-Object { $_ -like "*.*.*.*" })[0]
        } while ($ip -eq $null)
        Write-Output $ip                        
      register: vm_ip

    #Shutting down the VM to make some adjustments
    - name: System deployed, shutting down to configure Hyper-V
      win_shell: |
        $vm_name = '{{ lookup('env', 'code_projet') }}V{{ vm_type }}{{ next_vm_number.stdout | trim }}{{ lookup('env', 'environment') }}'
        $vm = Get-VM -Name $vm_name
        if ($vm.State -ne 'Off') {
          Stop-VM -VM $vm -Force
        }         

    #Secure boot
    - name: Enable Secure Boot with Microsoft UEFI Certificate Authority
      win_shell: |
        $vm_name = '{{ lookup('env', 'code_projet') }}V{{ vm_type }}{{ next_vm_number.stdout | trim }}{{ lookup('env', 'environment') }}'
        Set-VMFirmware -VMName "{{ item.name }}" -EnableSecureBoot On -SecureBootTemplate 'MicrosoftUEFICertificateAuthority'
      with_items: "{{ vms }}"

    #TPM
    - name: Enable TPM
      win_shell: |
        Import-Module Hyper-V
        $vm = Get-VM -Name "{{ lookup('env', 'code_projet') }}V{{ vm_type }}{{ next_vm_number.stdout | trim }}{{ lookup('env', 'environment') }}"
        $vm | Set-VMKeyProtector -NewLocalKeyProtector
        $vm | Enable-VMEncryption
        Enable-VMTPM -VMName "{{ lookup('env', 'code_projet') }}V{{ vm_type }}{{ next_vm_number.stdout | trim }}{{ lookup('env', 'environment') }}"
      with_items: "{{ vms }}"
      args:
        executable: powershell

    #Power on
    - name: Power on VM
      win_shell: |
        $vm_name = "{{ lookup('env', 'code_projet') }}V{{ vm_type }}{{ next_vm_number.stdout | trim }}{{ lookup('env', 'environment') }}"
        $vm = Get-VM -Name $vm_name
        if ($vm.State -eq 'Off') {
          Start-VM -VM $vm
        }

    #Pause to make sure everyting's up
    - name: Wait 1 minute for make sure VM fully booted up
      pause:
        minutes: 1

    #Network configuration over Hyper-V
    - name: Configure network
      win_shell: |
        $vm_name = '{{ lookup('env', 'code_projet') }}V{{ vm_type }}{{ next_vm_number.stdout | trim }}{{ lookup('env', 'environment') }}'
        Get-VMNetworkAdapter -VMName $vmname | Set-VMNetworkConfiguration -IPAddress {{ free_ip.stdout | trim }} -Subnet {{ network.subnet_mask }} -DNSServer {{ network.dns|join(",") }} -DefaultGateway {{ network.gateway }}

    #Additional storage configuration
    
############################DOUBLE QUOTES OBLIGATOIRES ?######################
######Sinon {{ vhdx_location }} =       - 'C:\ClusterStorage\Volume1\Hyper-V\DHIS'#######
    
    - name: Create and attach additional VHDX
      win_shell: |
        $vm_name = '{{ lookup('env', 'code_projet') }}V{{ vm_type }}{{ next_vm_number.stdout | trim }}{{ lookup('env', 'environment') }}'
        $vm = Get-VM -Name $vm_name
        $suffix = "{{ item.name }}"
        $path = "C:\\ClusterStorage\\Volume1\\Hyper-V\\DHIS\\${vm_name}-${suffix}.vhdx"
        $sizeGB = "{{ item.size[:-2] }}"
        $size = [int64]$sizeGB * 1GB
        if (-not (Test-Path $path)) {
          New-VHD -Path $path -Dynamic -SizeBytes $size
        }
        $existingVhd = Get-VMHardDiskDrive -VMName $vm.Name | Where-Object { $_.Path -eq $path }
        if ($existingVhd -eq $null) {
          Add-VMHardDiskDrive -VM $vm -Path $path
        }                
      loop: "{{ vhdx_suffixes }}"

    #Boot media removal
    - name: Remove DVD drive from VM
      win_shell: |
        $vm_name = '{{ lookup('env', 'code_projet') }}V{{ vm_type }}{{ next_vm_number.stdout | trim }}{{ lookup('env', 'environment') }}'
        $vm = Get-VM -Name $vm_name
        $dvdDrive = Get-VMDvdDrive -VM $vm
        if ($dvdDrive -ne $null)
        {
            $dvdDrive | Remove-VMDvdDrive -Confirm:$false
            Write-Output "DVD drive removed from the VM."
        }
        
    #Final DHCP entry update
    - name: Update RODC DHCP entry name
      win_shell: |
        $password = "{{ lookup('env', 'p') }}" | ConvertTo-SecureString -AsPlainText -Force
        $credential = New-Object System.Management.Automation.PSCredential ('{{ lookup('env', 'u') }}', $password)
        $subnet = "{{ lookup('env', 'subnet') }}.0"
        $name = "{{ code_projet }}V{{ type_machine }}{{ numero_machine }}{{ environnement }}.ocg.msf.org"
        $ipaddress = "{{ free_ip.stdout | trim }}"
        $clientid = "{{ mac_address.stdout | trim }}"

        $scriptBlock = {
          param($subnet, $ip_address)
          $reservation = Get-DhcpServerv4Reservation -ScopeID $subnet | Where-Object { $_.IPAddress -eq $ip_address }
          if ($reservation -ne $null) {
            Set-DhcpServerv4Reservation -ScopeID $subnet -ClientId $reservation.ClientId -Name {{ code_projet }}V{{ type_machine }}{{ numero_machine }}{{ environnement }}
          } else {
            Write-Host "No reservation found for $ip_address."
          }
        }

        Invoke-Command -ComputerName {{ target_RODC }} -Credential $credential -ScriptBlock $scriptBlock -ArgumentList $subnet, $name, $ipaddress, $clientid
        
    #VM deployed
    - name: Deployment done
      debug:
        msg: "DHIS deployment done. Machine name is {{ lookup('env', 'code_projet') }}V{{ vm_type }}{{ next_vm_number.stdout | trim }}{{ lookup('env', 'environment') }} and IP address is {{ free_ip.stdout | trim }}"